require 'opsicle/client'

require "opsicle/commands/chef_update"
require "opsicle/commands/deploy"
require "opsicle/commands/execute_recipes"
require "opsicle/commands/failure_log"
require "opsicle/commands/legacy_credential_converter"
require "opsicle/commands/list"
require "opsicle/commands/list_instances"
require "opsicle/commands/manage_aws_instances"
require "opsicle/commands/ssh"
require "opsicle/commands/ssh_clean_keys"
require "opsicle/commands/ssh_key"
require "opsicle/commands/update"
require "opsicle/commands/user_profile_info"
